# Generated by Django 5.1.5 on 2025-02-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ("-date_joined", "reason", "patient"),
                "verbose_name": "note",
                "verbose_name_plural": "notes",
            },
        ),
    ]
